[wallpaper]
name = "WebP Test"
author = "WLRS"
version = "1.0.0"
description = "A test wallpaper with WebP support"

[settings]
fps = 1
scale_mode = "fill"

[background]
image = "assets/background.webp"
color = "#000000"
