[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8"

[dev-dependencies]
tempfile = "3.8"
